apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: pet-store-db-credentials
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "DBCredentials"
          objectType: "secretsmanager"
          jmesPath: 
          - path: dbusername
            objectAlias: dbusername
          - path: dbpassword
            objectAlias: dbpassword